test_that("economic complexity measures are aligned with the expected output", {
  # matrix output ----
  ecm_n <- economic_complexity_measures(world_rca_2017)
  expect_is(ecm_n, "list")
  expect_is(ecm_n$economic_complexity_index, "numeric")
  expect_is(ecm_n$product_complexity_index, "numeric")
  expect_is(ecm_n$diversity, "numeric")
  expect_is(ecm_n$ubiquity, "numeric")
  expect_equal(length(ecm_n$economic_complexity_index), 224)
  expect_equal(length(ecm_n$product_complexity_index), 1222)
  expect_equal(length(ecm_n$diversity), 224)
  expect_equal(length(ecm_n$ubiquity), 1222)

  # tibble output ----
  ecm_t <- economic_complexity_measures(world_rca_2017, tbl_output = T)
  expect_is(ecm_t, "list")
  expect_is(ecm_t$economic_complexity_index, "data.frame")
  expect_is(ecm_t$product_complexity_index, "data.frame")
  expect_is(ecm_t$diversity, "data.frame")
  expect_is(ecm_t$ubiquity, "data.frame")
  expect_equal(nrow(ecm_t$economic_complexity_index), 224)
  expect_equal(ncol(ecm_t$economic_complexity_index), 2)
  expect_equal(nrow(ecm_t$product_complexity_index), 1222)
  expect_equal(ncol(ecm_t$product_complexity_index), 2)
  expect_equal(nrow(ecm_t$diversity), 224)
  expect_equal(ncol(ecm_t$diversity), 2)
  expect_equal(nrow(ecm_t$ubiquity), 1222)
  expect_equal(ncol(ecm_t$ubiquity), 2)
})
