test_that("complexity measures are aligned with the expected output", {
  # numeric output ----
  cm_n <- complexity_measures(world_rca_2017)
  expect_is(cm_n, "list")
  expect_is(cm_n$economic_complexity_index, "numeric")
  expect_is(cm_n$product_complexity_index, "numeric")
  expect_is(cm_n$diversity, "numeric")
  expect_is(cm_n$ubiquity, "numeric")
  expect_equal(length(cm_n$economic_complexity_index), 224)
  expect_equal(length(cm_n$product_complexity_index), 1222)
  expect_equal(length(cm_n$diversity), 224)
  expect_equal(length(cm_n$ubiquity), 1222)

  # tibble output ----
  cm_t <- complexity_measures(world_rca_2017, tbl_output = T)
  expect_is(cm_t, "list")
  expect_is(cm_t$economic_complexity_index, "data.frame")
  expect_is(cm_t$product_complexity_index, "data.frame")
  expect_is(cm_t$diversity, "data.frame")
  expect_is(cm_t$ubiquity, "data.frame")
  expect_equal(nrow(cm_t$economic_complexity_index), 224)
  expect_equal(ncol(cm_t$economic_complexity_index), 2)
  expect_equal(nrow(cm_t$product_complexity_index), 1222)
  expect_equal(ncol(cm_t$product_complexity_index), 2)
  expect_equal(nrow(cm_t$diversity), 224)
  expect_equal(ncol(cm_t$diversity), 2)
  expect_equal(nrow(cm_t$ubiquity), 1222)
  expect_equal(ncol(cm_t$ubiquity), 2)
})
