# Generated by cpp11: do not edit by hand

balassa_index_ <- function(trade_matrix, discrete, cutoff) {
  .Call(`_economiccomplexity_balassa_index_`, trade_matrix, discrete, cutoff)
}

fitness_method_ <- function(balassa_index, iterations, extremality) {
  .Call(`_economiccomplexity_fitness_method_`, balassa_index, iterations, extremality)
}

reflections_method_ <- function(balassa_index, iterations) {
  .Call(`_economiccomplexity_reflections_method_`, balassa_index, iterations)
}

eigenvalues_method_ <- function(balassa_index, iterations) {
  .Call(`_economiccomplexity_eigenvalues_method_`, balassa_index, iterations)
}

distance_ <- function(balassa_index, proximity_product) {
  .Call(`_economiccomplexity_distance_`, balassa_index, proximity_product)
}

proximity_ <- function(balassa_index, compute) {
  .Call(`_economiccomplexity_proximity_`, balassa_index, compute)
}
