# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title pairwise_max
#' @description
#' tbd
#' @name pairwise_max
#' @param n integer
#' @param k vector
#' @examples
#' #tbd
#' @export
pairwise_max <- function(n, k) {
    .Call(`_economiccomplexity_pairwise_max`, n, k)
}

